// Logos de cada entidad (íconos oficiales de sus apps en Google Play).
// Para agregar uno: el nombre tal cual aparece en tu hoja → la dirección de la imagen.
window.LOGOS = (function () {
  var P = 'https://play-lh.googleusercontent.com/';
  var L = {
    nequi: P + 'ieznb73N7P1gm49TTOYpQX23BAUlRVxiVnzy2_YJQSAkcfOkKOi9U-UQlvW5vCt1Exf2ljI-rn4Hc81xddqg5M8=s128',
    daviplata: P + 'bNPDiFqg28L6ckatfuP-WgrxDRDk0JEOkC6nUIQp7Q61RW78i1bw-ffMmEjyxl-qP6dv3ANDOQqmIbBtgJI3EA=s128',
    addi: P + '5Qf9j4iEBk0oLFA3HfR2UEu7ciowEeF9CA4N_-emk1VTmafE3f8EmBXP-ha0nHiIXDGwwvRCgXCK9TvyJMGLPZY=s128',
    nubank: P + 'FP6PILGwB6hrdvwg_mE8H1MKi2AcRDbHJcdg7WMfjiHbs4-ZZhYSMtgibkpeakstu1UeNHL4TGCo1l0mV2qkQa4=s128',
    davibank: P + 'MuPSLgt6NwvyLv-wFuXkXxXmrkaZufkzFd1nruNS7aiPQcQeMLQN5S7rMNR4Tv64ecTFT8sbDOpHhJC__qpatPU=s128',
    youtube: P + 'QNmuZQc9I6Zbe3mWnSr0hycnENqGFCI5p3yE29Hkxtf22T0IWS6zTrpxULLyyjWpB7ONAXDsDQXnXcVWokl3eg=s128',
    googleone: P + 'pnaxOl9i4YnkYKGMYkH17y_hA_FJOZRahlRGHQaaEGuLwPme68AfPShN2na5dEGOsem3hEzFvWXMz62WPVx8=s128',
    smartfit: P + 'yreG-gSxhCm1PDH6biQoIe-INRGOmQjbnIVsQThP6kv-Qbs7NZIXcBkwg3aoSx5xnQfH7Ky2Sz_PjLgKDlzY=s128',
    movistar: P + 'Hp05gIiG2qGoyyFKyxKnCA5fHmALq2Gp5L2dNYXtRXrDdiOw_4bZCJ9TgTqAjAuCrHWYLI3_wjLBHrejbX3u=s128',
    claude: P + 'YeFCFSW5LkBVdsEAL_fjzxDxTbhKz31j1uZUfDbSaCeM0t4Bi3SqyHTWzWsUsZnbwjofXhYajitG_gr2_B2xil8=s128',
    hevy: P + 'bLlRnwjt0tKva6ob0ZrtxkUs-z4MhQ4cPIOnXeh_knD8QVAXSLFiMGyKo2kLF7PV2uSK1Wly1L4q-6Sv1k13=s128',
    rappi: P + 'od9rcMwok9kSOE1nFhLFKyG1daEuexpf5Rpox1VrFnWxI_fNnjC_CtP-eKC2OkgkcOTPPics_q31ssn_OLyk=s128',
    credifin: 'https://www.google.com/s2/favicons?sz=128&domain=credifin.com.co',
    movies: 'logos/movies.png',
    terpel: P + '7QCowhje4Qmu4cM5lKw5T95Q_Wv3_Bm2SShhehki_S80NzOe103LY3-F-wrV2iJC3B0cLgePraT6oq-HbyKPKA=s128',
    jumbo: P + 'gJGDzHGgk33fW5cB--voYZQe3TDrOfMLq8bCFwxtdzNJGcELJzzYse6LEZK6Q1Ste8d0nCoqm7K2H55631FW=s128',
    metro: P + 'CbEXV98Ine68253x3Mo8Nq9Ho7_8FucUT6NZJvUf6F93ETKoBSuGLhspRIwT0oUHHK0VQJPjEyEmMdox_rtpfw=s128',
    exito: P + 'NZwOq9-pul-gVF0e9e0xcrt6OXAcJ5_Ur_rRszxkbsRxFWjdXIy5oXhiJ3HKeyQ9_TLhZK1HDQi7YpZZsTI1JA=s128',
    carulla: P + 'BAdVJ9RIIw3jscuSVf5VyEgKFSiOW6UUl5-HdUcPDoRxAF1GIqNpI4-t1XT1FheGWKWOUOMyJ1nkskSRjABA=s128',
    d1: P + 'PSeD3fbDcUs8J0gcbnwoY6-juhMYkN6Bo4h-rF89dtUXfjd0_8PwIApW7oPd2uBjzI56sVD1hBDWkxC5iiIb=s128',
    ara: P + 'sfKdZPGvpQF5bWF1CYQNWxw38nL9-pbLOX3AGV1eOGaOObvSupz3ws1cX2tT8NPZLf2JiCEAA_LAg7lEjuhr=s128'
  };
  // Comercios donde compras seguido: se reconocen por palabras en la descripción del movimiento.
  // Los que no tienen ícono oficial disponible se muestran con sus iniciales y colores de marca.
  window.COMERCIOS = [
    { p: /\b(terpel|eds)\b/, img: L.terpel, txt: 'TE', cat: 'Gasolina' },
    { p: /\bjumbo\b/, img: L.jumbo, txt: 'JU' },
    { p: /\bmetro\b/, img: L.metro, txt: 'ME' },
    { p: /\bexito\b/, img: L.exito, txt: 'ÉX' },
    { p: /\bcarulla\b/, img: L.carulla, txt: 'CA' },
    { p: /\bd1\b/, img: L.d1, txt: 'D1' },
    { p: /\bara\b/, img: L.ara, txt: 'AR' },
    { p: /\bisimo\b/, img: 'logos/isimo.png', txt: 'IS' },
    { p: /\bmakro\b/, img: 'logos/makro.png', txt: 'MK' },
    { p: /\bdollar ?city\b/, img: 'logos/dollarcity.png', txt: 'DC' },
    { p: /\btemu\b/, img: P + 'opNFHpwXUxk8zAVzQbvBgEcBPmgYt0uX-p28VKDZ8nJNFPA7_JHx3PO3ski-GW_FW7gf3jrEP4OCKxTpP7Wv_w=s128', txt: 'TE' },
    { p: /\bshein\b/, img: P + 'M_c3ZcQ1dx3AlDSfFEL0S2KgYrmkvJz2gz6gMZaL0pSQS9yYfUOGAQJTfuXMvx0K5c46dh5TKauxuRbUlnxB7w=s128', txt: 'SH' },
    { p: /\bmercado ?libre\b/, img: P + 'iVaeA0HDw8CZjEM-K7GdLB9XYmpcwVFSuv4Q8o9uh4Br7PuKCm3QSYCVU73tr9BBXdR_7xTX4yO0azOJegRVcA=s128', txt: 'ML' },
    { p: /\bamazon\b/, img: P + 'UIYZ9hTFNg-zZUg_uzLS9YdyDpvoo1VHNFb6VlzHy5JqNMq9Uq-p2S1VPwzXCipHTFacfGKhJkyAuKL19VVlcWA=s128', txt: 'AM' },
    { p: /\bali ?express\b/, img: P + 'VtiM0TOwAT4osyMK4Lm1duvGCBF-9y87pa2anqQfLBLc8modr2i-Pmin2uJHp4I14rIky_NLFCOC06dCPyZ1Cw=s128', txt: 'AE' },
    { p: /\brappi/, img: L.rappi, txt: 'RA' },
    { p: /\b(claude|anthropic)\b/, img: L.claude, txt: 'CL' },
    { p: /\byoutube\b/, img: L.youtube, txt: 'YT' },
    { p: /\bgoogle one\b/, img: L.googleone, txt: 'G1' },
    { p: /\bsmart ?fit\b/, img: L.smartfit, txt: 'SF' },
    { p: /\bmovistar\b/, img: L.movistar, txt: 'MO' },
    { p: /\bhevy\b/, img: L.hevy, txt: 'HV' },
    { p: /\bmovies/, img: L.movies, txt: 'MV' }
  ];
  return {
    'Nequi': L.nequi,
    'Daviplata': L.daviplata,
    'Bolsillo Daviplata TC Davibank': L.daviplata,
    'Addi': L.addi,
    'TC Nubank': L.nubank,
    'TC Davibank': L.davibank,
    'Credifin': L.credifin,
    'YouTube Premium': L.youtube,
    'Google One': L.googleone,
    'Smart Fit': L.smartfit,
    'Movistar Total': L.movistar,
    'Plan móvil mamá': L.movistar,
    'Claude': L.claude,
    'Hevy': L.hevy,
    'RappiPro': L.rappi,
    'Cuota de manejo Nubank': L.nubank,
    'Seguro de vida Davibank': L.davibank
  };
})();

// Diccionario automático: palabras de la descripción o del nombre → página web de la empresa.
// La app toma el logo de esa página (con las iniciales si no carga). Para mejorar uno, agrégalo arriba con su imagen.
window.DOMINIOS = [
  [/\b(olimpica)\b/, 'olimpica.com'],
  [/\b(pricesmart)\b/, 'pricesmart.com'],
  [/\b(colsubsidio)\b/, 'colsubsidio.com'],
  [/\b(surtimax)\b/, 'surtimax.com.co'],
  [/\b(super ?inter)\b/, 'superinter.com.co'],
  [/\b(euro ?supermercados)\b/, 'eurosupermercados.com.co'],
  [/\b(merqueo)\b/, 'merqueo.com'],
  [/\b(zapatoca)\b/, 'mercadoszapatoca.com'],
  [/\b(mercaldas)\b/, 'mercaldas.com'],
  [/\b(la vaquita)\b/, 'lavaquita.co'],
  [/\b(farmatodo)\b/, 'farmatodo.com.co'],
  [/\b(cruz ?verde)\b/, 'cruzverde.com.co'],
  [/\b(la rebaja)\b/, 'larebajavirtual.com'],
  [/\b(cafam)\b/, 'cafam.com.co'],
  [/\b(pasteur)\b/, 'farmaciaspasteur.com.co'],
  [/\b(locatel)\b/, 'locatelcolombia.com'],
  [/\b(drogueria alemana)\b/, 'drogueriaalemana.com'],
  [/\b(audifarma)\b/, 'audifarma.com.co'],
  [/\b(falabella)\b/, 'falabella.com.co'],
  [/\b(homecenter)\b/, 'homecenter.com.co'],
  [/\b(alkosto)\b/, 'alkosto.com'],
  [/\b(ktronix)\b/, 'ktronix.com'],
  [/\b(jamar)\b/, 'jamar.com'],
  [/\b(tugo)\b/, 'tugo.co'],
  [/\b(flamingo)\b/, 'flamingo.com.co'],
  [/\b(arturo ?calle)\b/, 'arturocalle.com'],
  [/\b(koaj)\b/, 'koaj.co'],
  [/\b(studio ?f)\b/, 'studiof.com.co'],
  [/\b(pat ?primo)\b/, 'patprimo.com'],
  [/\b(americanino)\b/, 'americanino.com'],
  [/\b(tennis)\b/, 'tennis.com.co'],
  [/\b(offcorss)\b/, 'offcorss.com'],
  [/\b(totto)\b/, 'totto.com'],
  [/\b(decathlon)\b/, 'decathlon.com.co'],
  [/\b(miniso)\b/, 'miniso.com.co'],
  [/\b(pepe ?ganga)\b/, 'pepeganga.com'],
  [/\b(panamericana)\b/, 'panamericana.com.co'],
  [/\b(libreria nacional)\b/, 'librerianacional.com'],
  [/\b(linio)\b/, 'linio.com.co'],
  [/\b(adidas)\b/, 'adidas.co'],
  [/\b(nike)\b/, 'nike.com'],
  [/\b(zara)\b/, 'zara.com'],
  [/\b(bershka)\b/, 'bershka.com'],
  [/\b(pull ?(&|and) ?bear)\b/, 'pullandbear.com'],
  [/\b(velez)\b/, 'velez.com.co'],
  [/\b(mario hernandez)\b/, 'mariohernandez.com.co'],
  [/\b(crocs)\b/, 'crocs.com.co'],
  [/\b(spring ?step)\b/, 'springstep.com.co'],
  [/\b(calzatodo)\b/, 'calzatodo.com.co'],
  [/\b(agaval)\b/, 'agaval.com'],
  [/\b(ikea)\b/, 'ikea.com'],
  [/\b(apple)\b/, 'apple.com'],
  [/\b(samsung)\b/, 'samsung.com'],
  [/\b(xiaomi)\b/, 'mi.com'],
  [/\b(claro)\b/, 'claro.com.co'],
  [/\b(tigo)\b/, 'tigo.com.co'],
  [/\b(wom)\b/, 'wom.co'],
  [/\b(etb)\b/, 'etb.com'],
  [/\b(directv)\b/, 'directv.com.co'],
  [/\b(win sports)\b/, 'winsports.co'],
  [/\b(mc ?donald)\b/, 'mcdonalds.com.co'],
  [/\b(automac)\b/, 'mcdonalds.com.co'],
  [/\b(kfc)\b/, 'kfc.com.co'],
  [/\b(burger ?king)\b/, 'burgerking.com.co'],
  [/\b(subway)\b/, 'subway.com'],
  [/\b(domino)\b/, 'dominos.com.co'],
  [/\b(papa ?john)\b/, 'papajohns.com.co'],
  [/\b(pizza ?hut)\b/, 'pizzahut.com.co'],
  [/\b(frisby)\b/, 'frisby.com.co'],
  [/\b(el corral)\b/, 'elcorral.com'],
  [/\b(presto)\b/, 'presto.com.co'],
  [/\b(crepes)\b/, 'crepesywaffles.com'],
  [/\b(juan ?valdez)\b/, 'juanvaldezcafe.com'],
  [/\b(starbucks)\b/, 'starbucks.com.co'],
  [/\b(qbano)\b/, 'sandwichqbano.com'],
  [/\b(kokoriko)\b/, 'kokoriko.com.co'],
  [/\b(mimos)\b/, 'mimos.com.co'],
  [/\b(dunkin)\b/, 'dunkin.com.co'],
  [/\b(popsy)\b/, 'popsy.com.co'],
  [/\b(archies)\b/, 'archies.co'],
  [/\b(wok)\b/, 'wok.com.co'],
  [/\b(jenos)\b/, 'jenospizza.com.co'],
  [/\b(tostao)\b/, 'tostao.com'],
  [/\b(gokana)\b/, 'gokana.com.co'],
  [/\b(sushi ?light)\b/, 'sushilight.com.co'],
  [/\b(cinemark)\b/, 'cinemark.com.co'],
  [/\b(cine ?colombia)\b/, 'cinecolombia.com'],
  [/\b(procinal)\b/, 'procinal.com.co'],
  [/\b(royal ?films)\b/, 'royal-films.com'],
  [/\b(tu ?boleta)\b/, 'tuboleta.com'],
  [/\b(primax)\b/, 'primax.com.co'],
  [/\b(texaco)\b/, 'texaco.com'],
  [/\b(biomax)\b/, 'biomax.co'],
  [/\b(mobil)\b/, 'mobil.com.co'],
  [/\b(esso)\b/, 'esso.com'],
  [/\b(zeuss)\b/, 'zeuss.com.co'],
  [/\b(uber)\b/, 'uber.com'],
  [/\b(didi)\b/, 'didiglobal.com'],
  [/\b(indrive)\b/, 'indrive.com'],
  [/\b(cabify)\b/, 'cabify.com'],
  [/\b(picap)\b/, 'picap.app'],
  [/\b(avianca)\b/, 'avianca.com'],
  [/\b(latam)\b/, 'latamairlines.com'],
  [/\b(jet ?smart)\b/, 'jetsmart.com'],
  [/\b(wingo)\b/, 'wingo.com'],
  [/\b(satena)\b/, 'satena.com'],
  [/\b(flypass)\b/, 'flypass.com.co'],
  [/\b(transmilenio)\b/, 'transmilenio.gov.co'],
  [/\b(copetran)\b/, 'copetran.com.co'],
  [/\b(berlinas)\b/, 'berlinasdelfonce.com'],
  [/\b(bolivariano)\b/, 'bolivariano.com.co'],
  [/\b(expreso brasilia)\b/, 'expresobrasilia.com'],
  [/\b(netflix)\b/, 'netflix.com'],
  [/\b(spotify)\b/, 'spotify.com'],
  [/\b(disney)\b/, 'disneyplus.com'],
  [/\b(hbo)\b/, 'max.com'],
  [/\b(prime ?video)\b/, 'primevideo.com'],
  [/\b(amazon prime)\b/, 'primevideo.com'],
  [/\b(crunchyroll)\b/, 'crunchyroll.com'],
  [/\b(paramount)\b/, 'paramountplus.com'],
  [/\b(deezer)\b/, 'deezer.com'],
  [/\b(apple (music|tv|one))\b/, 'apple.com'],
  [/\b(icloud)\b/, 'icloud.com'],
  [/\b(google play)\b/, 'play.google.com'],
  [/\b(chat ?gpt)\b/, 'openai.com'],
  [/\b(openai)\b/, 'openai.com'],
  [/\b(gemini)\b/, 'gemini.google.com'],
  [/\b(microsoft)\b/, 'microsoft.com'],
  [/\b(office 365)\b/, 'microsoft.com'],
  [/\b(canva)\b/, 'canva.com'],
  [/\b(adobe)\b/, 'adobe.com'],
  [/\b(duolingo)\b/, 'duolingo.com'],
  [/\b(platzi)\b/, 'platzi.com'],
  [/\b(coursera)\b/, 'coursera.org'],
  [/\b(xbox)\b/, 'xbox.com'],
  [/\b(playstation)\b/, 'playstation.com'],
  [/\b(steam)\b/, 'steampowered.com'],
  [/\b(nintendo)\b/, 'nintendo.com'],
  [/\b(dropbox)\b/, 'dropbox.com'],
  [/\b(notion)\b/, 'notion.so'],
  [/\b(zoom)\b/, 'zoom.us'],
  [/\b(tinder)\b/, 'tinder.com'],
  [/\b(bumble)\b/, 'bumble.com'],
  [/\b(linkedin)\b/, 'linkedin.com'],
  [/\b(capcut)\b/, 'capcut.com'],
  [/\b(fitia)\b/, 'fitia.app'],
  [/\b(myfitnesspal)\b/, 'myfitnesspal.com'],
  [/\b(bodytech)\b/, 'bodytech.com.co'],
  [/\b(spinning center)\b/, 'spinningcenter.com.co'],
  [/\b(bancolombia)\b/, 'bancolombia.com'],
  [/\b(davivienda)\b/, 'davivienda.com'],
  [/\b(banco de bogota)\b/, 'bancodebogota.com'],
  [/\b(bbva)\b/, 'bbva.com.co'],
  [/\b(banco popular)\b/, 'bancopopular.com.co'],
  [/\b(banco de occidente)\b/, 'bancodeoccidente.com.co'],
  [/\b(av ?villas)\b/, 'avvillas.com.co'],
  [/\b(colpatria)\b/, 'scotiabankcolpatria.com'],
  [/\b(scotiabank)\b/, 'scotiabankcolpatria.com'],
  [/\b(itau)\b/, 'itau.co'],
  [/\b(caja social)\b/, 'bancocajasocial.com'],
  [/\b(banco agrario)\b/, 'bancoagrario.gov.co'],
  [/\b(banco falabella)\b/, 'bancofalabella.com.co'],
  [/\b(cmr)\b/, 'bancofalabella.com.co'],
  [/\b(pichincha)\b/, 'bancopichincha.com.co'],
  [/\b(gnb)\b/, 'gnbsudameris.com.co'],
  [/\b(lulo)\b/, 'lulobank.com'],
  [/\b(rappi ?(pay|card))\b/, 'rappipay.co'],
  [/\b(movii)\b/, 'movii.com.co'],
  [/\b(uala)\b/, 'uala.com.co'],
  [/\b(global ?66)\b/, 'global66.com'],
  [/\b(sistecredito)\b/, 'sistecredito.com'],
  [/\b(lineru)\b/, 'lineru.com'],
  [/\b(rapicredit)\b/, 'rapicredit.com'],
  [/\b(efecty)\b/, 'efecty.com.co'],
  [/\b(western union)\b/, 'westernunion.com'],
  [/\b(paypal)\b/, 'paypal.com'],
  [/\b(mercado ?pago)\b/, 'mercadopago.com.co'],
  [/\b(confiar)\b/, 'confiar.coop'],
  [/\b(sura)\b/, 'segurossura.com.co'],
  [/\b(sanitas)\b/, 'epssanitas.com'],
  [/\b(compensar)\b/, 'compensar.com'],
  [/\b(coomeva)\b/, 'coomeva.com.co'],
  [/\b(nueva eps)\b/, 'nuevaeps.com.co'],
  [/\b(seguros bolivar)\b/, 'segurosbolivar.com'],
  [/\b(allianz)\b/, 'allianz.co'],
  [/\b(mapfre)\b/, 'mapfre.com.co'],
  [/\b(porvenir)\b/, 'porvenir.com.co'],
  [/\b(colpensiones)\b/, 'colpensiones.gov.co'],
  [/\b(colfondos)\b/, 'colfondos.com.co'],
  [/\b(comfanorte)\b/, 'comfanorte.com.co'],
  [/\b(comfenalco)\b/, 'comfenalco.com'],
  [/\b(dian)\b/, 'dian.gov.co'],
  [/\b(runt)\b/, 'runt.com.co'],
  [/\b(simit)\b/, 'fcm.org.co'],
  [/\b(registraduria)\b/, 'registraduria.gov.co'],
  [/\b(epm)\b/, 'epm.com.co'],
  [/\b(enel)\b/, 'enel.com.co'],
  [/\b(codensa)\b/, 'enel.com.co'],
  [/\b(vanti)\b/, 'grupovanti.com'],
  [/\b(acueducto)\b/, 'acueducto.com.co'],
  [/\b(emcali)\b/, 'emcali.com.co'],
  [/\b(celsia)\b/, 'celsia.com'],
  [/\b(cens)\b/, 'cens.com.co'],
  [/\b(aguas kpital)\b/, 'aguaskpital.com.co'],
  [/\b(kpital)\b/, 'aguaskpital.com.co'],
  [/\b(gases del oriente)\b/, 'gasesdeloriente.com'],
  [/\b(gases del caribe)\b/, 'gascaribe.com'],
  [/\b(air-?e)\b/, 'air-e.com'],
  [/\b(afinia)\b/, 'afinia.com.co'],
  [/\b(laika)\b/, 'laika.com.co'],
  [/\b(puppis)\b/, 'puppis.com.co']
];
window.logoDe = function (texto) {
  var t = String(texto || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[’'`]/g, '');
  for (var i = 0; i < window.DOMINIOS.length; i++) {
    if (window.DOMINIOS[i][0].test(t)) return 'https://www.google.com/s2/favicons?sz=128&domain=' + window.DOMINIOS[i][1];
  }
  return '';
};
