// Logos de cada entidad (íconos oficiales de sus apps en Google Play).
// Para agregar uno: el nombre tal cual aparece en tu hoja → la dirección de la imagen.
window.LOGOS = (function () {
  var P = 'https://play-lh.googleusercontent.com/';
  var L = {
    nequi: P + 'ieznb73N7P1gm49TTOYpQX23BAUlRVxiVnzy2_YJQSAkcfOkKOi9U-UQlvW5vCt1Exf2ljI-rn4Hc81xddqg5M8=s128',
    daviplata: P + 'bNPDiFqg28L6ckatfuP-WgrxDRDk0JEOkC6nUIQp7Q61RW78i1bw-ffMmEjyxl-qP6dv3ANDOQqmIbBtgJI3EA=s128',
    addi: P + '5Qf9j4iEBk0oLFA3HfR2UEu7ciowEeF9CA4N_-emk1VTmafE3f8EmBXP-ha0nHiIXDGwwvRCgXCK9TvyJMGLPZY=s128',
    nubank: P + 'FP6PILGwB6hrdvwg_mE8H1MKi2AcRDbHJcdg7WMfjiHbs4-ZZhYSMtgibkpeakstu1UeNHL4TGCo1l0mV2qkQa4=s128',
    davibank: P + 'MuPSLgt6NwvyLv-wFuXkXxXmrkaZufkzFd1nruNS7aiPQcQeMLQN5S7rMNR4Tv64ecTFT8sbDOpHhJC__qpatPU=s128',
    youtube: P + 'QNmuZQc9I6Zbe3mWnSr0hycnENqGFCI5p3yE29Hkxtf22T0IWS6zTrpxULLyyjWpB7ONAXDsDQXnXcVWokl3eg=s128',
    googleone: P + 'pnaxOl9i4YnkYKGMYkH17y_hA_FJOZRahlRGHQaaEGuLwPme68AfPShN2na5dEGOsem3hEzFvWXMz62WPVx8=s128',
    smartfit: P + 'yreG-gSxhCm1PDH6biQoIe-INRGOmQjbnIVsQThP6kv-Qbs7NZIXcBkwg3aoSx5xnQfH7Ky2Sz_PjLgKDlzY=s128',
    movistar: P + 'Hp05gIiG2qGoyyFKyxKnCA5fHmALq2Gp5L2dNYXtRXrDdiOw_4bZCJ9TgTqAjAuCrHWYLI3_wjLBHrejbX3u=s128',
    claude: P + 'YeFCFSW5LkBVdsEAL_fjzxDxTbhKz31j1uZUfDbSaCeM0t4Bi3SqyHTWzWsUsZnbwjofXhYajitG_gr2_B2xil8=s128',
    hevy: P + 'bLlRnwjt0tKva6ob0ZrtxkUs-z4MhQ4cPIOnXeh_knD8QVAXSLFiMGyKo2kLF7PV2uSK1Wly1L4q-6Sv1k13=s128',
    rappi: P + 'od9rcMwok9kSOE1nFhLFKyG1daEuexpf5Rpox1VrFnWxI_fNnjC_CtP-eKC2OkgkcOTPPics_q31ssn_OLyk=s128',
    credifin: 'https://icons.duckduckgo.com/ip3/credifin.com.co.ico',
    movies: 'logos/movies.png',
    terpel: P + '7QCowhje4Qmu4cM5lKw5T95Q_Wv3_Bm2SShhehki_S80NzOe103LY3-F-wrV2iJC3B0cLgePraT6oq-HbyKPKA=s128',
    jumbo: P + 'gJGDzHGgk33fW5cB--voYZQe3TDrOfMLq8bCFwxtdzNJGcELJzzYse6LEZK6Q1Ste8d0nCoqm7K2H55631FW=s128',
    metro: P + 'CbEXV98Ine68253x3Mo8Nq9Ho7_8FucUT6NZJvUf6F93ETKoBSuGLhspRIwT0oUHHK0VQJPjEyEmMdox_rtpfw=s128',
    exito: P + 'NZwOq9-pul-gVF0e9e0xcrt6OXAcJ5_Ur_rRszxkbsRxFWjdXIy5oXhiJ3HKeyQ9_TLhZK1HDQi7YpZZsTI1JA=s128',
    carulla: P + 'BAdVJ9RIIw3jscuSVf5VyEgKFSiOW6UUl5-HdUcPDoRxAF1GIqNpI4-t1XT1FheGWKWOUOMyJ1nkskSRjABA=s128',
    d1: P + 'PSeD3fbDcUs8J0gcbnwoY6-juhMYkN6Bo4h-rF89dtUXfjd0_8PwIApW7oPd2uBjzI56sVD1hBDWkxC5iiIb=s128',
    ara: P + 'sfKdZPGvpQF5bWF1CYQNWxw38nL9-pbLOX3AGV1eOGaOObvSupz3ws1cX2tT8NPZLf2JiCEAA_LAg7lEjuhr=s128'
  };
  // Comercios donde compras seguido: se reconocen por palabras en la descripción del movimiento.
  // Los que no tienen ícono oficial disponible se muestran con sus iniciales y colores de marca.
  window.COMERCIOS = [
    { p: /\b(terpel|eds)\b/, img: L.terpel, txt: 'TE', cat: 'Gasolina' },
    { p: /\bjumbo\b/, img: L.jumbo, txt: 'JU' },
    { p: /\bmetro\b/, img: L.metro, txt: 'ME' },
    { p: /\bexito\b/, img: L.exito, txt: 'ÉX' },
    { p: /\bcarulla\b/, img: L.carulla, txt: 'CA' },
    { p: /\bd1\b/, img: L.d1, txt: 'D1' },
    { p: /\bara\b/, img: L.ara, txt: 'AR' },
    { p: /\bisimo\b/, img: 'logos/isimo.png', txt: 'IS' },
    { p: /\bmakro\b/, img: 'logos/makro.png', txt: 'MK' },
    { p: /\bdollar ?city\b/, img: 'logos/dollarcity.png', txt: 'DC' },
    { p: /\btemu\b/, img: P + 'opNFHpwXUxk8zAVzQbvBgEcBPmgYt0uX-p28VKDZ8nJNFPA7_JHx3PO3ski-GW_FW7gf3jrEP4OCKxTpP7Wv_w=s128', txt: 'TE' },
    { p: /\bshein\b/, img: P + 'M_c3ZcQ1dx3AlDSfFEL0S2KgYrmkvJz2gz6gMZaL0pSQS9yYfUOGAQJTfuXMvx0K5c46dh5TKauxuRbUlnxB7w=s128', txt: 'SH' },
    { p: /\bmercado ?libre\b/, img: P + 'iVaeA0HDw8CZjEM-K7GdLB9XYmpcwVFSuv4Q8o9uh4Br7PuKCm3QSYCVU73tr9BBXdR_7xTX4yO0azOJegRVcA=s128', txt: 'ML' },
    { p: /\bamazon\b/, img: P + 'UIYZ9hTFNg-zZUg_uzLS9YdyDpvoo1VHNFb6VlzHy5JqNMq9Uq-p2S1VPwzXCipHTFacfGKhJkyAuKL19VVlcWA=s128', txt: 'AM' },
    { p: /\bali ?express\b/, img: P + 'VtiM0TOwAT4osyMK4Lm1duvGCBF-9y87pa2anqQfLBLc8modr2i-Pmin2uJHp4I14rIky_NLFCOC06dCPyZ1Cw=s128', txt: 'AE' },
    { p: /\brappi/, img: L.rappi, txt: 'RA' },
    { p: /\b(claude|anthropic)\b/, img: L.claude, txt: 'CL' },
    { p: /\byoutube\b/, img: L.youtube, txt: 'YT' },
    { p: /\bgoogle one\b/, img: L.googleone, txt: 'G1' },
    { p: /\bsmart ?fit\b/, img: L.smartfit, txt: 'SF' },
    { p: /\bmovistar\b/, img: L.movistar, txt: 'MO' },
    { p: /\bhevy\b/, img: L.hevy, txt: 'HV' },
    { p: /\bmovies/, img: L.movies, txt: 'MV' }
  ];
  return {
    'Nequi': L.nequi,
    'Daviplata': L.daviplata,
    'Bolsillo Daviplata TC Davibank': L.daviplata,
    'Addi': L.addi,
    'TC Nubank': L.nubank,
    'TC Davibank': L.davibank,
    'Credifin': L.credifin,
    'YouTube Premium': L.youtube,
    'Google One': L.googleone,
    'Smart Fit': L.smartfit,
    'Movistar Total': L.movistar,
    'Plan móvil mamá': L.movistar,
    'Claude': L.claude,
    'Hevy': L.hevy,
    'RappiPro': L.rappi,
    'Cuota de manejo Nubank': L.nubank,
    'Seguro de vida Davibank': L.davibank
  };
})();

// Diccionario automático: palabras de la descripción o del nombre → empresa.
// Tercer dato: ícono oficial de su app en Google Play (verificado por nombre y desarrollador).
// Sin ícono de app se usa el logo de su página web; si nada carga, salen las iniciales.
window.DOMINIOS = [
  [/\b(olimpica)\b/, 'olimpica.com', 'YCFsgTtrlGYT7mtvUYU0oXpMdvFZoiSihzOGjz9VN7ZlqgsqThmIpkWiREsX72JEg06UYjYsb0ExWISCs9McPw'],
  [/\b(pricesmart)\b/, 'pricesmart.com', 'o1dtpN5Jr1oHIqTacc0iWGlMaw7kNhB8aWxbMlNw5QfD5s2q7AFWUKjz9f3aaipcE5_thIt-4AH83fuvstp9PQ'],
  [/\b(colsubsidio)\b/, 'colsubsidio.com', '2_8cAajXPw8-teADiLS1revAkg8IPgHaylU89A_N96ZqHsTzy9GQjLNnedvNDj2O8-JIzQDHfjeozjVoC8L_zWU'],
  [/\b(surtimax)\b/, 'surtimax.com.co'],
  [/\b(super ?inter)\b/, 'superinter.com.co'],
  [/\b(euro ?supermercados)\b/, 'eurosupermercados.com.co'],
  [/\b(merqueo)\b/, 'merqueo.com'],
  [/\b(zapatoca)\b/, 'mercadoszapatoca.com'],
  [/\b(mercaldas)\b/, 'mercaldas.com', 'XeQNkYJVtAzDE5wV4pnugLr4HIkjNWo4ncXzAdFJMu5WKM16Cnx2UyM_dkzPUusNqzKLIIvfmRRYLvE2vxKo'],
  [/\b(la vaquita)\b/, 'lavaquita.co'],
  [/\b(farmatodo)\b/, 'farmatodo.com.co', 'O31qOhyk16MPku6rs5WDW9UJBwMXf5BLLC6-LlWZHO8jY0fMqDQCZp38uZh6rxq6TXNuSH1kE47sbBtxEZBe'],
  [/\b(cruz ?verde)\b/, 'cruzverde.com.co', '3Cd5RfSJgj8UBwL2E6sNRFbPHtbtNfrYs7x75zlau7o1gAkBt91ucayH32C5pctmmRpmGe_reWbEzD1HsrydnCU'],
  [/\b(la rebaja)\b/, 'larebajavirtual.com', 'MZorv_6kY46-64lKQLnSiIKFdvLHVBbuwY9K1Iz_1AW7o24-nubwtDSpUgJ02qQwq6fTme0CY_Gs0hDhii19Iw'],
  [/\b(cafam)\b/, 'cafam.com.co'],
  [/\b(pasteur)\b/, 'farmaciaspasteur.com.co'],
  [/\b(locatel)\b/, 'locatelcolombia.com'],
  [/\b(drogueria alemana)\b/, 'drogueriaalemana.com'],
  [/\b(audifarma)\b/, 'audifarma.com.co', 'PC8T-p6xMmdNjWN3z5bsYxuV3qD0Y9O6HKQ9SXtJkB2IJ1ai9RW1fQNTzYtiOZIaJQ1iko0EVHIlejKBTg0r5g'],
  [/\b(falabella)\b/, 'falabella.com.co', 'RIwZY3yNQ8yTqVxQYWqsLKp5onKvMvpe_-1WQT2Udke_wAXGXaxQOVFf5b9V-StzpT2kbWfI4l7es-_N8SpiQw'],
  [/\b(homecenter)\b/, 'homecenter.com.co', 'ETeHEfJaBBMfM12FBJZKmw0Dezef-VvP_9F5dfIEKImthFgyVyDr5LHP0so4rVoEkSYYuirYFCe50KnR0twWIYQ'],
  [/\b(alkosto)\b/, 'alkosto.com', 'MssM6iqq-VIx6t00lND2Vy01_Yb0a7SgBJFR1jShKKqQY5oO_O5SLKSRf0You44TtJTJmgjFmaaI2C1Rg3VkcQ'],
  [/\b(ktronix)\b/, 'ktronix.com', 'qUUqM_0RmrmxDaJtkIn7DrNZ0m25uS7KWW4zVXIHGB3cXn7JU_QhXvdUKQxvSKdYutFGBx8WSnd5pMZe5LP8Vq0'],
  [/\b(jamar)\b/, 'jamar.com', 'eV48MRJEBqJPPf7EsUA0_Nya0dgj6KHfzf-IM6VjSXfmahXtDCvTXCNzvg4MpibNb24qMTnC9t6Qthq9dzou'],
  [/\b(tugo)\b/, 'tugo.co'],
  [/\b(flamingo)\b/, 'flamingo.com.co', 'VVMA_XOQmSCK2PSP7WD_-GZTQNrIcZ3bhtHdItm2_QY46QjPMgwiuJe3aIl6GpKePp7T80YFPXRiDTdaR224'],
  [/\b(arturo ?calle)\b/, 'arturocalle.com'],
  [/\b(koaj)\b/, 'koaj.co', 'As7ZZZbD7u2bQqQM1LuJMqTg6xW_lcBU3-i4FS4LIFWamgphj6DL3hxQ-GMfD6vjFovvc0ZW1SF9xrmLaI9MOQ'],
  [/\b(studio ?f)\b/, 'studiof.com.co'],
  [/\b(pat ?primo)\b/, 'patprimo.com', 'IYIAVJkl7HM94ZpimAjs1Cvn8lOUjTeZwnuP7VMeOERFqG_wU_w2Et4AFs0Sfb1DKjBsgPxZ_73mIvnOe-VROA'],
  [/\b(americanino)\b/, 'americanino.com'],
  [/\b(tennis)\b/, 'tennis.com.co'],
  [/\b(offcorss)\b/, 'offcorss.com'],
  [/\b(totto)\b/, 'totto.com'],
  [/\b(decathlon)\b/, 'decathlon.com.co', 'Sd6ZYTZP7qz0j0WSQ6bX5TGMxVtMZvA9L-HZY5j9xBNund197M9QHJbopyYIJMjIvrFG-w-axi4sdhOLmxh4iA'],
  [/\b(miniso)\b/, 'miniso.com.co', 'VyhCgsaswMTS2uecGNThMlLuEbRU5uavD1BVRNbD7CTDucKyoN5AvyQz0lk0pF0WQXJcH0uKdOm5-l9sQrTvq7k'],
  [/\b(pepe ?ganga)\b/, 'pepeganga.com', '0Qtsrq6iWri8JosmzncBCm4QWVTXxsYVPjCs7NIxeJUgvEPkQqulXswR15abWhW9-C8rtOEXraM47y0CS8CI'],
  [/\b(panamericana)\b/, 'panamericana.com.co'],
  [/\b(libreria nacional)\b/, 'librerianacional.com'],
  [/\b(linio)\b/, 'linio.com.co'],
  [/\b(adidas)\b/, 'adidas.co', 'Yhi36qdNE50yM5ZLVxN-SXORNDiSbw5-6NJ5AzoR6paHsk_6d__-FaIydmoglCAsGAzgaYLlkO69i80G2NYBl74'],
  [/\b(nike)\b/, 'nike.com'],
  [/\b(zara)\b/, 'zara.com', 'zfZXuUlI9Jwzfy7b9oZnmtrNosRnoVrfuBKUeWEMrg5msz3VWHum3JcGW811I2EqSzfOeIil14KQ7cZLguXNLw'],
  [/\b(bershka)\b/, 'bershka.com', 'ujONZM_f7IcfCPNxRXwCZwM4d7vUMPUZitfNdlvnJiPn65H7UyFZ_WSp9S9IebwanB_3f-tTr_FzqiD5wdiD'],
  [/\b(pull ?(&|and) ?bear)\b/, 'pullandbear.com'],
  [/\b(velez)\b/, 'velez.com.co'],
  [/\b(mario hernandez)\b/, 'mariohernandez.com.co', 'xsPlfrxDBVbG6FprmKyxXvxOn0PkIxxFVngBkMPV5qnVdtTpLZ1rRKVR_LoLdMF5g8fFcGih7bYMdZOtO0KZ'],
  [/\b(crocs)\b/, 'crocs.com.co'],
  [/\b(spring ?step)\b/, 'springstep.com.co'],
  [/\b(calzatodo)\b/, 'calzatodo.com.co'],
  [/\b(agaval)\b/, 'agaval.com'],
  [/\b(ikea)\b/, 'ikea.com'],
  [/\b(apple)\b/, 'apple.com'],
  [/\b(samsung)\b/, 'samsung.com'],
  [/\b(xiaomi)\b/, 'mi.com'],
  [/\b(claro)\b/, 'claro.com.co', 'oBBmhzPBNzD-R88BQ2xoL0_phqEjGUkIhaYv2-EKo-3dufR_fmWgIYSJ-ENdAIkFb1_pzuyu7gU8BMNm3lLkuw'],
  [/\b(tigo)\b/, 'tigo.com.co', 'eyt6JoS8zSkOY-za2i88oFqdeWQnjpGn_Y9cKoWr2113Vs5wVRpRPx82QWZKVjIcf4nAtdhkzYYuAvIlZr2NkQ'],
  [/\b(wom)\b/, 'wom.co', 'uIYm9vGcvBhz-EgqPNnK6lJqjEHUu16DdviQjxKWIa-cLdznAxOTPIed2szqcTkvVbWFJU2nfnywOYAIHzdL'],
  [/\b(etb)\b/, 'etb.com', '9ITICd5vDeweo1GA5DqS55hjy_VhLxIrIcSHL8D1wJ0rp3HESvDZJ6XDiQYuBBfcGe4XYWOzHpA1DydgrHtHMA'],
  [/\b(directv)\b/, 'directv.com.co', 'aBCiBm81ykOiwQRXYravN7ZozSWGGzVLphQxTHR0DBEco9fWOb3Q5CaiMmWJT2TuTHVU3xC_YHRTTf2JkoAaYVE'],
  [/\b(win sports)\b/, 'winsports.co'],
  [/\b(mc ?donalds?)\b/, 'mcdonalds.com.co', 'SUc2UKYeeaw88w8s9GWUiCTcuAdgGUgN-dU1OQj3LN8sYk5wOlvEpkA2pdwJ5ulN-1tUWyTplH1cGShBdab3'],
  [/\b(automac)\b/, 'mcdonalds.com.co', 'SUc2UKYeeaw88w8s9GWUiCTcuAdgGUgN-dU1OQj3LN8sYk5wOlvEpkA2pdwJ5ulN-1tUWyTplH1cGShBdab3'],
  [/\b(kfc)\b/, 'kfc.com.co', 'aesSBO5MRY2G7i-giN8NcN9wY7nTqEeTeavYVfCZInQbprqGMcgse0IQOsRLBsQoIrm9MQ9Vb6DhZDNV0QNX'],
  [/\b(burger ?king)\b/, 'burgerking.com.co', 'aNj0XA66W4APMtVoaFTwa9rP-ypVtY4E8_yWYErt_Ach8QFcIDlfKT2VB0yS_C7AoYnGT7QfumZ7Dqn3QEp1TVo'],
  [/\b(subway)\b/, 'subway.com'],
  [/\b(domino)\b/, 'dominos.com.co'],
  [/\b(papa ?johns?)\b/, 'papajohns.com.co', 'V8lBJj952y2sCBX5SKHOl8z1_G9jlC5klrCdJTtmMZR9TESqnJfCLhMjCsaRdxlxEhtCZr53w5AiIxhMIHfg'],
  [/\b(pizza ?hut)\b/, 'pizzahut.com.co', 'HBf7cNUKNVuLOpf_Q74W7LbcvEt0IXyRovr_9oo3puGaK78BGJ1GqbHzhDkXqaqZ0rvR_5-Wp2ZvlN2Cy4bdXw'],
  [/\b(frisby)\b/, 'frisby.com.co', 'PKzn29J04rvqvJ2CwPNZ6FbVfmE4DH-JOAN-3ZIGbPfF0fmqVL5CTRb0ZTJ2g7K1HXrX_WC5El4e5qD_8YCn'],
  [/\b(el corral)\b/, 'elcorral.com', 'f_QrYqAIDJ2brk63w4MVVkwfm9NltZovV1zUwS7BJX2t8SgrFepaf-p1UQRbspPrG9ZgCz9-sn4IMypcykztcg'],
  [/\b(presto)\b/, 'presto.com.co'],
  [/\b(crepes)\b/, 'crepesywaffles.com'],
  [/\b(juan ?valdez)\b/, 'juanvaldezcafe.com', 'Oya6YNtXBAbrweJ2rS6pf1yinVSA9BgTiLNLv6AMA0jlX7gxS4Ybrk0VbaAsGv7YLCY_6TZL_XeoGPIfV7ptdg'],
  [/\b(starbucks)\b/, 'starbucks.com.co', '5CDVOSP6Xnf-AEgYLgJqeqa7QC01GIMpM1P5e7dkieW7dnufF40bhVgqqDoGW1fSETxdBbcT1nikmjBU3ihzmA'],
  [/\b(qbano)\b/, 'sandwichqbano.com'],
  [/\b(kokoriko)\b/, 'kokoriko.com.co'],
  [/\b(mimos)\b/, 'mimos.com.co'],
  [/\b(dunkin)\b/, 'dunkin.com.co', 'xoVNvzFCouJ3VRWHsjCpAA8fEECZQMYGNcgXoIwD_Gfw6BZZFVJPDId78A5HYMGC4tydlFO9V1SAR3GFE6kJwg'],
  [/\b(popsy)\b/, 'popsy.com.co'],
  [/\b(archies)\b/, 'archies.co'],
  [/\b(wok)\b/, 'wok.com.co'],
  [/\b(jenos)\b/, 'jenospizza.com.co'],
  [/\b(tostao)\b/, 'tostao.com'],
  [/\b(gokana)\b/, 'gokana.com.co'],
  [/\b(sushi ?light)\b/, 'sushilight.com.co'],
  [/\b(cinemark)\b/, 'cinemark.com.co', 'rM4fup6gXIio6QlxCOvhcbM-p7gBl5XGcJojU7MmmNkKhekC3g8zd_5RWB0Lt-oSXZBAstOT406E2QG7g70G'],
  [/\b(cine ?colombia)\b/, 'cinecolombia.com'],
  [/\b(procinal)\b/, 'procinal.com.co', 'oQBQdolYEqxJ-6kAa0OasvJ5HXVLG72kJmSRQLCTr7CaZQ7gnKiLLNDI8OM8HY-4jcS_y-6zl4noWlvD496-Wkc'],
  [/\b(royal ?films)\b/, 'royal-films.com', 'rmS_XqeansBLj8lnRLz8KmO7e07-chXsUVMA0CW4ixA_9a9c_DOHQSvYLRB0ajaVwCizs0KkQfvFFdHQZHAdcZY'],
  [/\b(tu ?boleta)\b/, 'tuboleta.com', 'JDnfI4sQu0GssuiALzxz0e5SpMpiLVUcy5rQXOPOvvkqj7P6NczlJEEUkBg6XPH1ioFSnGNF3VVJ8DrW3Juu9_I'],
  [/\b(primax)\b/, 'primax.com.co'],
  [/\b(texaco)\b/, 'texaco.com'],
  [/\b(biomax)\b/, 'biomax.co'],
  [/\b(mobil)\b/, 'mobil.com.co'],
  [/\b(esso)\b/, 'esso.com'],
  [/\b(zeuss)\b/, 'zeuss.com.co', 'B5yD9MYRUBO1V38Ojj-EdJWCzAmYzAUum3VJKuynAsQalflJGd50QermTShMLh5wLKvwbo002A35s1JY7v3V3Q'],
  [/\b(uber)\b/, 'uber.com', 'OXQnDlRtPa5ha6KCnKPqVmxHYBP7tjrAa7PXGNRqcwDC_J03HVeuEKcKrkcIqnfOqsF5uy3uwWxIXR067QHsNQ'],
  [/\b(didi)\b/, 'didiglobal.com', 'w08P6Py2wtGkmuBbwQ6KDV6t9hqwy3nNI6SKrQg4wxT6j6vCY2evsDGzXk6q0KGeeTmX8ij9uoOxuH1YOIFtC7A'],
  [/\b(indrive)\b/, 'indrive.com', '3jQ0FcHlGVSTTjy3oEmSenrtSN_XRs4JZxzLZtbJWni-NLWA24N9N_HFmTrlkDpAedfZXEeTUNtW0qdkklzGEdM'],
  [/\b(cabify)\b/, 'cabify.com', '7F3WB7mlIU8sW_CA1VsrRZGm8WxfJ7CXVkfPOBYyCgafbjpuCMOdO3dNa-RsgCIvZccyucv7JqHcUd7Vxn5qYuA'],
  [/\b(picap)\b/, 'picap.app', 'FAwY6u379vvPX5h1cJ3GfbwVUSKLJ7aTvHrdVeDBfdUAtHHonZ3CJcvssQYgTZoOfWTRSHvujr48gfgm0kSp2g'],
  [/\b(avianca)\b/, 'avianca.com', '2qLwxi8EJ9qwDFjVQrSWjFo5gSAbRFgcm_65AatToV9aqqYCAkDmxpw9gqD6w8Z1RqTxnhcT0nde86cWtlbHaQ'],
  [/\b(latam)\b/, 'latamairlines.com', 'AJJhe5P-fK7ofdTAN88kDJaCLUPDLdWYoI756WoY7i1WRzp4HFgSH4qZDGvXtrjFZAbGZKQ3wMKeL39phRi6-w'],
  [/\b(jet ?smart)\b/, 'jetsmart.com', '_xFbYAMcEPHAuVtXj4qG9xTpSrGA7ve1YzuOORgmZd3OYwUL0ab25AkNcLgzGCgY5I_qrQ6n-zmiTofGapjNloM'],
  [/\b(wingo)\b/, 'wingo.com', '3dEKqVEc6KbSanF-V8BjufhpMdgR5-BgfYYmZt-C743ULavFW65Ap__cOpW7E_wU2xNtz-HV3q0m6GPqiHPP7g'],
  [/\b(satena)\b/, 'satena.com'],
  [/\b(flypass)\b/, 'flypass.com.co', 'R0LtQIhvB8qSpkkWHz7zt4b9Uwd-RxYsHC273Lnowyz-YVIw0juDM2nHbt5N_6z_5ua2vcXQB54g4MR8gR63Eg'],
  [/\b(transmilenio)\b/, 'transmilenio.gov.co', 'U7rgNsal5Fvo5LFZF5Fv1GWF_at0medEyLtkz6sNoHlOp229_lKO3wdWwtatRbKT1MAdiZQyEHgHHlUKLLJL5w'],
  [/\b(copetran)\b/, 'copetran.com.co', '-ggNrZ3pFE66Y12rFHOd6ADo_7HYw7UH1Qf6LcEFAw24UyGmu28b2NR1f-UyopzuHpL0D0RNXxOU-tYWkW5q'],
  [/\b(berlinas)\b/, 'berlinasdelfonce.com', '0mKm4pguf1QBMmCdKJfEx-RSe5D476zuApg8rKWRnuMNgar1hQWforqdepa6PuoFFLji6aiGE7FZj3kWQhuglPA'],
  [/\b(bolivariano)\b/, 'bolivariano.com.co', '9eSqWT0mU0TC468g3RtavbZdu3ipE1nwqkHT7tergfyR2ybw4M2GNoTwE-0yAjqyTgBXvPw4rduCIbQ0fiXJ410'],
  [/\b(expreso brasilia)\b/, 'expresobrasilia.com', 'FiIj1N8IMS8R3uDmr3DbomYdDrGzEGzlsDyYmU8WIW9IzUVgI1wIuA7tvBOfRvRO1DmKgpmTBfsbpL1SLGS6Aw'],
  [/\b(netflix)\b/, 'netflix.com', 'fXVS45nukV1x9PYVSKHkCQK0QGCOishIvAOxIZS3sgRem8HS7l9l94_Ggj-WZPrTLePRdNYN4pp4SPAQL7oS0PU'],
  [/\b(spotify)\b/, 'spotify.com', 'IzQgYCcnCFCD08GR-3bdtcT8xzOvrNkC84avGT5CwTX2VIqmTmKKJcP_Cd4JoBOdmCMlTndlOzV6hrthg2fOWA'],
  [/\b(disney)\b/, 'disneyplus.com', 'AEX_3Bk5_SEZfR4fUcJsWiyqW_RRVcLED9AM2HMUVHAPVTZhZHfP2q3M35mRe4LtCXlb712DtkKwkZa_nJ-0'],
  [/\b(hbo)\b/, 'max.com', 'wKJ5hN5CmSBWXPBVYYuRENzcEVb7FB6NyibjKqPT4SB0eoZ7Fww2jq-OhUDCxEPGALrSekQaazrHLSBwVb6T4A'],
  [/\b(prime ?video)\b/, 'primevideo.com', 'NnoDzfxkvlsAvU8jzoPeK8aaxbcU2sEH_btwgMQ2xI88_qtrNGQuf1vlFkxSiQODyKVFZ3-s71sU1MHyV-vc9Q'],
  [/\b(amazon prime)\b/, 'primevideo.com', 'NnoDzfxkvlsAvU8jzoPeK8aaxbcU2sEH_btwgMQ2xI88_qtrNGQuf1vlFkxSiQODyKVFZ3-s71sU1MHyV-vc9Q'],
  [/\b(crunchyroll)\b/, 'crunchyroll.com', 'FUEOotGzxEZqItvGGov0YBiOhZBCACxCM6kF37OtpWrCG9H6EyxSeY2G8PDXQGueLxlxtL3Xr0fbkvXaQ67NLg'],
  [/\b(paramount)\b/, 'paramountplus.com', 'yU3omfdofyeO2Zfz1nYNc80-UajN2aR7HHcCZty45mI5dZW1QAz1PUdeI2t67UAldSk0PIyJoUkNIMS8HmdyRQ'],
  [/\b(deezer)\b/, 'deezer.com', 'RFBXn4V0H8Zmi3_jViu73GTpQOmGmrvG7mdM1ynStAAYEd2aOLo5G0v9AHSUMwia1lQGI-c5oXMzZJCq0RMlJA'],
  [/\b(apple (music|tv|one))\b/, 'apple.com'],
  [/\b(icloud)\b/, 'icloud.com'],
  [/\b(google play)\b/, 'play.google.com'],
  [/\b(chat ?gpt)\b/, 'openai.com', 'T9J8e9oxxPd600j_KPM4KK2GHfNpUpGBdTy8lHPXBXpOUfGusRuZXj0UMgFNrP8we6LVt9V-AibEgcLootE6VK4'],
  [/\b(openai)\b/, 'openai.com', 'T9J8e9oxxPd600j_KPM4KK2GHfNpUpGBdTy8lHPXBXpOUfGusRuZXj0UMgFNrP8we6LVt9V-AibEgcLootE6VK4'],
  [/\b(gemini)\b/, 'gemini.google.com', 'C64IqPWyFoCZzXVxXVl0Y6mliiNlG_sZJsqul-SBvk9ZL0wJHlU0Eho2wvsBHhho0FT5XQtH55RVGerIwXF_MA'],
  [/\b(microsoft)\b/, 'microsoft.com'],
  [/\b(office 365)\b/, 'microsoft.com'],
  [/\b(canva)\b/, 'canva.com', '52fzAlhKzDyZV8ttyQ_DHB-jOeLZAZEdKlgXnWL__YNMZuvsoRCshJX5mr_ArFZjK7rte4hqEJ4ucjtuKJK5'],
  [/\b(adobe)\b/, 'adobe.com'],
  [/\b(duolingo)\b/, 'duolingo.com', 'Q-wEiKezZQEspFNNrWfKjcEgAqdWy_b98_tXTAZaXGgm9y1HZ1zi-JSZXA7Tmur9MjcM0xoIA0BdXEN0Bt54'],
  [/\b(platzi)\b/, 'platzi.com', 'G_o_GpBC-qdbHixIBNwWkraoRK9sd7T_XqyJvaZYnT-m2p_8mUcbkB4nBskQg9V_OOCgRt6q-n4L8TPhrd3J'],
  [/\b(coursera)\b/, 'coursera.org', 'LbjoYTPK5ZlNO3GDMZsFoGoRXHLoA2iTAUvJF7ePRZzbRPu7En-Go3wWXPXEdCL6grpkPHHavvzalozZrbJi'],
  [/\b(xbox)\b/, 'xbox.com', 'zARzhQw-V25X6KCiciynwWtlzOfaS41kx2rZYecxPoY5Z248n-d3lyotuKL0fJYLEvQQ40QNsx8J2VSm2G7RjA'],
  [/\b(playstation)\b/, 'playstation.com', '3Y2xJ77Ucj7Ovxf12AbJszkAqttbJfiO7DOjK9NO8vQn57Rar8uhkgcwbXFu2k7eXZR-Z0_Nbo8NWKfZjkDsRQ'],
  [/\b(steam)\b/, 'steampowered.com', 'E_x2GPSJakCdUYfECBptVyFoVnC4BxIPy3K4OdbwNyEtEJkRAY_J-Lo_Ltiybq6LiJ_aZCIzvqLv5h4Fbk91'],
  [/\b(nintendo)\b/, 'nintendo.com', 'SEeC6HgdR8G8yVL6av9PJtZA1cGSW0IiI98f_OQpTXhUZtzR3KcwQgjzvYg8nA5yImAwsbUfegX035EyxUmYpQ'],
  [/\b(dropbox)\b/, 'dropbox.com', 'A8rNctsbRVnv05n6gwR74kN68SuSaBW-B9NTdCrq62snoMxMnedV2PGZaatv-sPS9ygdVvXUomyRfGWa8Xul1Q'],
  [/\b(notion)\b/, 'notion.so', '-GY1Xv9hhhK_RFJCCb-rvDX8OMR8Fj68AgcRIFcD8zIXlOA8pG-L-cuOJbgSs_U6GGGyGs8qiiQsjIfEBazE8g'],
  [/\b(zoom)\b/, 'zoom.us', '-Ajlo-aDBHtpCez_yILc8Kepv_kNhbTJPw1WyvXgkh4O-hvUN-YD_v_0FlJmgRbZ2vn1OmZCmCBOY23h4kJYEA'],
  [/\b(tinder)\b/, 'tinder.com', 'VaExVMyjnrd9PkIAKchSBK6Eo7zb4A2rriDbD3pUvmveAy46StPS-Hs5mYVIP9upZV4YCJxRoQRnj77FAaQd2A'],
  [/\b(bumble)\b/, 'bumble.com', '7GSSxUQ2KneDsNK1KIlBa26ukNM6UmOtpfAVSj-72Im-62jd1-38et6VEqBD-LKfXZdGHQfucP3tVOIGa3kV'],
  [/\b(linkedin)\b/, 'linkedin.com', 'oij55bxj3e-4JrhGntpki0lnQyE8yQn8X5FPEzZ0t7cLppeiSINynEk7n9COoh7QSaCOZ_yiPO31NVaW4SDbWg'],
  [/\b(capcut)\b/, 'capcut.com', 'M78HyakHaxKrjoeqYx41E9DXfVYYtx67nvc7Ks4G4zFQeaAJdGCi8gzzGSrHIwlrmnJS6zD9S4fAXqdEwfuHQAQ'],
  [/\b(fitia)\b/, 'fitia.app', 'mJGJbyI6KAfa4RfGX2uehPoceAl1abtme6J8WcqxhOkuUkQcZbq1MKZpSTkToMusytCpA-uf1_D21JrSHiInEA'],
  [/\b(myfitnesspal)\b/, 'myfitnesspal.com', 'VDmmLoS__AlWJdUzOEOaw9dukSLIFlhehgV0FgqShqhQ7kHVkH0k4QImbjeX_CKCz2UfUhZ9NH0441ZqnLQV'],
  [/\b(bodytech)\b/, 'bodytech.com.co', 'yoMnBAVfDIsFi4-agKHN4_8ysc0ddsHxE4XwpB-m_oXxxVKVmjVFa_bFgvs4NX2mEdseeQYJ3ZnARnufyNZ5KoU'],
  [/\b(spinning center)\b/, 'spinningcenter.com.co', 'XSVp8WFIkPUqfHHRC05cVj_-lJ0ZOlz1G10ouQosJfqYrvQfe7DKzT4Y3Dzmja_g0jmpDY9Cp5H_VLnakBCk'],
  [/\b(bancolombia)\b/, 'bancolombia.com', '691aSBrPfXMjtthQ7o-qHCaYhf9-XTSxrxGAp7XzrlGzxys8jQ8JrGjUuuUwxVJwSMj1DfRq6UxSYFTrM5jZ8g'],
  [/\b(davivienda)\b/, 'davivienda.com', 'pox0Q0f9dLVaXdYCq-3T6l6DCxbuouxH2vlnYFlIndog9vKTrzZHpMWaRhLZ6IZatq6Lulw6rbsKqAoXRtqEZpc'],
  [/\b(banco de bogota)\b/, 'bancodebogota.com', 'nXPTmRreiRkIxUKiQ4-CNGx3n2HmiJ0v43WJZ0P7pK-SYDN_57Z2Tp86V54q-z-noDGT7MIu3PeTdm2GIvakwA'],
  [/\b(bbva)\b/, 'bbva.com.co', 'MAJJ2PZ8t2Ifs3Naf6GBQV3ROoUHNDrvNsBZUD6pVrMwxmehKh7rSUyHEyC7MI_ptY7VSkbqZ8QWg1_h7Iz2'],
  [/\b(banco popular)\b/, 'bancopopular.com.co', '6b84Dw0kMc9XN97kRCdfQ2ID8AYHAYvpFS0LZzfHJq41M6FA1CnWG1oWOXvUOJ2ufzdSFfFnPAjdYC6Rz6xl'],
  [/\b(banco de occidente)\b/, 'bancodeoccidente.com.co', 'JU1nNiVxhWxvJgCwJosGWLEfLmGKCBkluOdlqfuNZnlkVhGe1qcCJnQJRkGQJD1xnNQhlvE_1bQN_bqLC8BICJE'],
  [/\b(av ?villas)\b/, 'avvillas.com.co', 'tgsJcZ0kwGBHWS3uvKI0B-H1zfi3vvySX9VGhGwNvCmpcmMRQ_F30G3JsNMsjTmrRD_pGjmujTGzV4mDDWnU'],
  [/\b(colpatria)\b/, 'scotiabankcolpatria.com'],
  [/\b(scotiabank)\b/, 'scotiabankcolpatria.com'],
  [/\b(itau)\b/, 'itau.co', 'TTzHZIn-jjXoADJ09NSrc0WRnrODhKjtAJj801dvQUPmbMwfRx2N40liORJyh-gaq-vD7jHAkSHYs_23pENTSw'],
  [/\b(caja social)\b/, 'bancocajasocial.com', 'gSN9iRjqtGKlSLTaX4OTbanXoc_nU1_tpy8Q4XitHWeYxMCyQcLrUkaHWvxPdhMHGftb6pVAD-kE-6wJ7csq'],
  [/\b(banco agrario)\b/, 'bancoagrario.gov.co', 'avOZyjlGHYKB4rj5pyXrXBo4g6DSNHeaUQc0-1JopInnOll8aUqa8jouKRUCQJ88vREd990PY4NpLcERynAhHQ'],
  [/\b(banco falabella)\b/, 'bancofalabella.com.co', '2JeGuXJhl6J-LaVb_FtOvwcQfNeiKDxLcP4k6QSXpJSndwSvA6HYb_OJB0SgW_7KHbadwFdlgThSiB2mrjs1bg'],
  [/\b(cmr)\b/, 'bancofalabella.com.co', '2JeGuXJhl6J-LaVb_FtOvwcQfNeiKDxLcP4k6QSXpJSndwSvA6HYb_OJB0SgW_7KHbadwFdlgThSiB2mrjs1bg'],
  [/\b(pichincha)\b/, 'bancopichincha.com.co', 'zshMjTiM7J5lvZSD-ocJCbeRBx-PtPBQZb6wFfxI4_5mBMQoInjru3teWRS0RfmszPGLn3iS27JF1SA1oynAReM'],
  [/\b(gnb)\b/, 'gnbsudameris.com.co', '6lM662pKnMbFr4vxZ2nNIzGxu67sNnfrLMG80nVK-UxVNocfoTQDOXNtC8evv4c_Mmui_suclQC0XmHz3VH9'],
  [/\b(lulo)\b/, 'lulobank.com', '1K0r8g8YCQh_GpVdeBmCIM_ZKdl8Ykis2i6RLd-XeKv-m9wvDy1I-W13b1rzsOm64hezDvGilQQXMHt0FIwyKg'],
  [/\b(rappi ?(pay|card))\b/, 'rappipay.co', 'od9rcMwok9kSOE1nFhLFKyG1daEuexpf5Rpox1VrFnWxI_fNnjC_CtP-eKC2OkgkcOTPPics_q31ssn_OLyk'],
  [/\b(movii)\b/, 'movii.com.co', 'gETGEwCduyqlz7Fm9iTu9_IgpqLJO88P7vBl-rVr6PO2fhX6ftWDkKz0CmaiSEQWcYm2Z4CCgcrNSOwEmR9pfQ'],
  [/\b(uala)\b/, 'uala.com.co', 'Qdkf9ZzC7lChjw9QJdpMqtwXNt-Jj2AY8Fzl10-PDqRR5Nh4QBe0qqr0aM_AxasWOuk3CISwEeIY-hYjJALU'],
  [/\b(global ?66)\b/, 'global66.com', '9b6J_oX-1DYPf-Tp6VyjItQnOcovg8hKCJLjaR2LZlT2C1CGqywlugTVsLMiyB_9MYiURqDS2FeFIih45qxWYQ'],
  [/\b(sistecredito)\b/, 'sistecredito.com', 'bg4zjZ1hsGX42Q9JYVALDasxijoMhqM8FqsgRBSN4dntaEoqgofmnuaYMBRdQVcgIWCZOdN_8hqUYZzpAdO8oQ'],
  [/\b(lineru)\b/, 'lineru.com'],
  [/\b(rapicredit)\b/, 'rapicredit.com', 'Qb0R9z7DrqgWyxU3QzN9vyXHJqrRFlWSibwn-t7wuclkzJT5M4Pryz-KuQRH4xAqCLXiQfHz3TPTBC816VDYDf0'],
  [/\b(efecty)\b/, 'efecty.com.co', '-6lavYbHUBORFor3Eo4vWMiPUSzf-a38URrzM_pgXuE76dhd1tXEMDpb8GXKRWRT5_aZY4c2wJ0rNOMmnq7L'],
  [/\b(western union)\b/, 'westernunion.com', 'To2aXUcEIwzr6JV0JQJRuaTKsOLALQtcptHw45svMEc0iboY_zWTPEAfNg6pVMHrEcdDXU60Cl-nqV0ay52xLA'],
  [/\b(paypal)\b/, 'paypal.com', '9SeHb3IaNFm7sXRQmWZaL5MHqVn4qcBGz12sPgjBisZCFMyZPOCXUFOZIttUu-CiTqQz3alXL7jxxGW1Y4fn'],
  [/\b(mercado ?pago)\b/, 'mercadopago.com.co', '-WB4u-r62cAEy8kImGb4-pXGcr2T-nC71c54xJO4m1aIRtKb2eI2pW_rm7AZg6tEpOL1ZTdIiozUMHgA6eZFl9Y'],
  [/\b(confiar)\b/, 'confiar.coop', '-qtwdlarkECfuCKNjRlymdtzjoVMTWVeDMQ2qzmeNc0roOMUftrmOjcVO2swhvwjspFEkYgKRhpU6lqgzdshQ6s'],
  [/\b(sura)\b/, 'segurossura.com.co', '5NfR-wFzfzLDusB2kxDjNMS8qI7AEb0KznOLa3U5lN31eNDaJT_mthWdcrvjjT9urBngBUS_Y0Y3hxTgvRBBIA'],
  [/\b(sanitas)\b/, 'epssanitas.com', '8KLP2cDq0k9b9RmX8epDKFcc4kMJusnQ7mN1yAHtaLD06a9goVDmvtr6M6ZidHoUypfmF-06CFzrBVBeW5-2IQ'],
  [/\b(compensar)\b/, 'compensar.com', 'o-SGKvZhRrbzQGu1jjnPEPG33LLRdnPOB46_nqVkydEUIHoHS9LbpqIyo77qMc1B9syYEFDuPF-5GxYITp0u'],
  [/\b(coomeva)\b/, 'coomeva.com.co', 'XoytA5NqjbA_iYxI_7RQQE5so5uvjp2j7q7AdH7nhvJgtQfRTijluDu25Is_433xkxJtjYfB7yD6Eln_K9ExbA'],
  [/\b(nueva eps)\b/, 'nuevaeps.com.co', 'NDyIRsUGpHdBBjBHfcSuj-0FBmupHiPcjDDO_fPllj0ctZSdSBzaMTKyW-sSdtHQA-xI8idIqh9y8_epT96yNw'],
  [/\b(seguros bolivar)\b/, 'segurosbolivar.com'],
  [/\b(allianz)\b/, 'allianz.co', 'a-a_a6y0_jj1Y1tSko9IvwlqoQXweH3T5AuNnfXspBG-SUxD1Tsf1ibzlJrsflsOCvsSNAB9M9RTohuMofVy2g'],
  [/\b(mapfre)\b/, 'mapfre.com.co', 'styud5_52bB3QWFSbbiQOP81Eu5KLf61ADdnRv_VJh_VyY37mas90lUxK5wbJeFy8cmJVpDYmn29rGCs5eRU'],
  [/\b(porvenir)\b/, 'porvenir.com.co', 'Zokdqh95nneoH8KMFqnwvnCuQGShGcn_8ot2zBZkIand7zTvmH8x6xyBMjRpF_v1vrJh6qwNtDXoRdZjaBmwacE'],
  [/\b(colpensiones)\b/, 'colpensiones.gov.co', 'yuw_O8zlIgYsrd5Cgji0G9IMk-TFQenWQQ5uN6UkdUEzxOZygwOcXC3mVzsTv-5ADy0AxMfyH6w0mZfNk3BfWA'],
  [/\b(colfondos)\b/, 'colfondos.com.co'],
  [/\b(comfanorte)\b/, 'comfanorte.com.co'],
  [/\b(comfenalco)\b/, 'comfenalco.com'],
  [/\b(dian)\b/, 'dian.gov.co'],
  [/\b(runt)\b/, 'runt.com.co', 'XWfkGt7Vh5XaMVBn9wt4tbUbnj_0UMzp7ChaluFRer4SRxlTwljdq4hW6ifKjps1cQCw7oYb1YPLbkGtDiuLlok'],
  [/\b(simit)\b/, 'fcm.org.co', 'Ct3c9njGFqfbt2DhGR-PafkjN8J0vGyAvPvnH6894G9QIKBTpAzaXmq8QnKc3ipt8lpgtm6yir7-_Z2Yrs65Cw'],
  [/\b(registraduria)\b/, 'registraduria.gov.co', 'j5dxnz-RL-QfiEPvK48K2XwMz7r7x56KnjscLZaADDeVHg92vqItAsZLkCUkUToXWk_WfAydggaylRMcUCxAfAw'],
  [/\b(epm)\b/, 'epm.com.co', 'yYbIE5PDuVFKQGf96aKXfgA-4D2U2t8ThW9Ws1ei5sdK7taaVwKhKZtWWlm2HIyo6N3_ML-3tZkS-BiZSpN4'],
  [/\b(enel)\b/, 'enel.com.co', 'i5D83LJWEcdItqXX_RRA0Xpi38eJsumWnw7aQmG1qXvpVwYXrt-4OBkpQ48TlCbvsbirxH3ryPLXz1rcMi_bdHY'],
  [/\b(codensa)\b/, 'enel.com.co', 'i5D83LJWEcdItqXX_RRA0Xpi38eJsumWnw7aQmG1qXvpVwYXrt-4OBkpQ48TlCbvsbirxH3ryPLXz1rcMi_bdHY'],
  [/\b(vanti)\b/, 'grupovanti.com'],
  [/\b(acueducto)\b/, 'acueducto.com.co', 'btt7cAdRGhYg9bKoP_Cw77dp6kv9JYW4AKhrt64mpHOUqb0QkwXeUMIxyh2F41ftq0oLQgXKlEXF39QNlISu'],
  [/\b(emcali)\b/, 'emcali.com.co'],
  [/\b(celsia)\b/, 'celsia.com', '-F0Cxop0XCPFEGQIfRnwPFRmoEocGlc98M1tKXeCYYzgKcX-QTREIMsuIyReSQP0-uMXuX6JR2iqs-rsTWnCXKI'],
  [/\b(cens)\b/, 'cens.com.co', 'Wdp6Tb_rESjZbL2gYYfpMFjmc-BjB9SjWqQaFkTVhL5_asy5hNq0qgIW8N-_2uQ_SCJyVhxPDqc0ep3xwngTwQ'],
  [/\b(aguas kpital)\b/, 'aguaskpital.com.co'],
  [/\b(kpital)\b/, 'aguaskpital.com.co'],
  [/\b(gases del oriente)\b/, 'gasesdeloriente.com', '565ASVH7-pvL2gvqVn0Fg7hL3sm0YEMAM4NWMlB0rqJD3mSmx1aPR_RYp-ibHzGjkEaZX8GZgcXWOwWfnUUMrQ'],
  [/\b(gases del caribe)\b/, 'gascaribe.com', 'Z_06fJbBW3zv1ulH_iymynzA8autp9KPdgaC7bANmrdA78CsKyTFnLMBsvtoaOQJfiohDLyDxRLCd8h6XMC9UA'],
  [/\b(air-?e)\b/, 'air-e.com'],
  [/\b(afinia)\b/, 'afinia.com.co', 'SrrH_d0Gww5OYP1RIsvlT-dOAp1-Q1U6jGjLuUnhDKRG7Or-L7OeQGwaHHK3KqCZiSbiWIq3y_Rcm6kSVn3u'],
  [/\b(laika)\b/, 'laika.com.co', 'UtN3Mbg0URtjDDCZGLYtBZBWhSWlbPfNjZJpogOaoxweP_9mCVdxlNSv1NBFz8c0qE7VuWfRsEYoBrpgXJ4Buuk'],
  [/\b(puppis)\b/, 'puppis.com.co']
];
function buscarDominio(texto) {
  var t = String(texto || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[’'`]/g, '');
  for (var i = 0; i < window.DOMINIOS.length; i++) if (window.DOMINIOS[i][0].test(t)) return window.DOMINIOS[i];
  return null;
}
window.logoDe = function (texto) {
  var d = buscarDominio(texto);
  if (!d) return '';
  return d[2] ? 'https://play-lh.googleusercontent.com/' + d[2] + '=s128' : 'https://www.google.com/s2/favicons?sz=128&domain=' + d[1];
};
// Segunda opción si la primera imagen no carga (logo de la página web por otro servicio).
window.logoRespaldo = function (texto) {
  var d = buscarDominio(texto);
  return d ? 'https://icons.duckduckgo.com/ip3/' + d[1] + '.ico' : '';
};
